version: "2"

services:
  django:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src/_static:/usr/src/app/_static

  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ../../data/mysql:/var/lib/mysql

  redis:
    image: redis

  postgres:
    image: postgres
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    volumes:
      - ../../data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
